site_name: Magnus Extensions
site_description: "Extends magnus to Cloud"
strict: true
repo_url: https://github.com/AstraZeneca/magnus-extensions

docs_dir: "docs"
theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  font: false
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    - scheme: default
      primary: amber
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky

# Extensions
markdown_extensions:
  - pymdownx.snippets:
      base_path: "docs"
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
      separator: "_"
      toc_depth: 2
  - attr_list
  - md_in_html
plugins:
  - search

nav:
  - "Home": "index.md"
  - "Installation": "installation.md"
  - "Executor":
      - "Kubeflow": "executor/kfp.md"
      - "Argo": "executor/argo.md"
  - "Catalog":
      - "S3": "catalog/s3.md"
  # - "Secrets":
  #     - "AWS Secrets Manager": "secrets/aws_secrets_manager.md"
  - "Run Log Store":
      - "S3": "run_log_store/s3.md"
      - "Chunked S3": "run_log_store/chunked-s3.md"
      #- "Database": "run_log_store/database.md"
  #- "Experiment Tracking":
