import logging

from magnus.integration import BaseIntegration
from magnus import defaults

logger = logging.getLogger(defaults.NAME)


class K8sPollerComputeRunLogStoreBuffered(BaseIntegration):
    """
    Integration between k8s-poller and Buffered as run log store
    """
    mode_type = 'k8s-poller'
    service_type = 'run_log_store'  # One of secret, catalog, datastore
    service_provider = 'buffered'  # The actual implementation of the service

    def validate(self, **kwargs):
        msg = (
            f"Compute mode {self.mode_type} is not compatible with {self.service_provider} for {self.service_type}"
        )
        raise Exception(msg)


class K8sPollerComputeRunLogStoreFileSystem(BaseIntegration):
    """
    Integration between k8s-poller and file-system as run log store
    """
    mode_type = 'k8s-poller'
    service_type = 'run_log_store'  # One of secret, catalog, datastore
    service_provider = 'file-system'  # The actual implementation of the service

    def validate(self, **kwargs):
        msg = (
            f"Compute mode {self.mode_type} is not compatible with {self.service_provider} for {self.service_type}"
        )
        raise Exception(msg)


class K8sPollerComputeRunLogStoreS3(BaseIntegration):
    """
    Integration between k8s-poller and file-system as run log store
    """
    mode_type = 'k8s-poller'
    service_type = 'run_log_store'  # One of secret, catalog, datastore
    service_provider = 's3'  # The actual implementation of the service

    def validate(self, **kwargs):
        if self.executor.is_parallel_execution():
            msg = (
                'Run log generated by S3 run log store are not thread safe. '
                'Inconsistent results are possible because of race conditions to write to the same file.\n'
                'Consider using partitioned run log store like database for consistent results.'

            )
            logger.warning(msg)


class K8sPollerComputeCatalogFileSystem(BaseIntegration):
    """
    Integration between k8s-poller and file-system as catalog
    """
    mode_type = 'k8s-poller'
    service_type = 'catalog'  # One of secret, catalog, datastore
    service_provider = 'file-system'  # The actual implementation of the service

    def validate(self, **kwargs):
        msg = (
            f"Compute mode {self.mode_type} is not compatible with {self.service_provider} for {self.service_type}"
        )
        raise Exception(msg)
