mode:
  type: k8s-poller  
  config:
    image_name: harbor.csis.astrazeneca.net/dataiku/hello-magnus:latest
    namespace: test
    config_path: ~/.kubeconfig
    polling_time: 30
    secrets_to_use: ["afe-sit", "afe-aws-dev"]
    enable_parallel: "False"

run_log_store:
  type: s3
  config:
    s3_bucket: az-eu-dataiku-science-development
    region: eu-west-1 # defaults to eu-west-1
    use_credentials: True
    prefix: magnus

catalog:
  type: s3
  config:
    s3_bucket: az-eu-dataiku-science-development
    region: eu-west-1 # defaults to eu-west-1
    use_credentials: True
    prefix: magnus/catalog

secrets:
  type: env-secrets-manager