site_name: Magnus Extensions
site_description: "Extends magnus"

docs_dir: "docs"
theme:
  name: material
  font: false
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - tabs
    - navigation.top
    - toc.integrate
    - search.suggest

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
      separator: "_"
      toc_depth: 2

plugins:
  - search

nav:
  - "Home": "index.md"
  - "Cloud Configuration":
      - "AWS": "aws.md"
  #- "Executor":
  - "Catalog":
      - "S3": "catalog/s3.md"
  - "Secrets":
      - "AWS Secrets Manager": "secrets/aws_secrets_manager.md"
  - "Run Log Store":
      - "S3": "run_log_store/s3.md"
      - "Database": "run_log_store/database.md"
  #- "Experiment Tracking":
